version: '3.8'
services:
backend:
build: ./backend
ports:
- '8000:8000'
environment:
- OPENAI_API_KEY=${OPENAI_API_KEY}
- PINECONE_API_KEY=${PINECONE_API_KEY}
frontend:
build: ./frontend
ports:
- '3000:3000'
environment:
- NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
